name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v6
      with:
        php_version: 8.1
    - uses: php-actions/phpunit@v3
      with:
        configuration: phpunit.xml
        php_version: 8.1
        version: 8.5
        php_extensions: xdebug
